name: CD vers Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image Docker
        run: docker build -t websocket-app:${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag et Push vers Docker Hub
        run: |
          docker tag websocket-app:${{ github.sha }} kenlark/websocket-app:latest
          docker push kenlark/websocket-app:latest

      - name: Déploiement vers Render via HTTP API
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-${RENDER_SERVICE_ID} \
            -H 'Authorization: Bearer '"$RENDER_API_KEY" \
            -H 'Accept: application/json'
